# Generated by Django 4.2.1 on 2023-06-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_alter_profesional_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPaterno', models.CharField(max_length=50)),
                ('rut', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('tipos_contacto', models.IntegerField(choices=[[0, 'sugerencia'], [1, 'Reclamo']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
