# Generated by Django 4.2.1 on 2023-06-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_rename_apellidopaterno_contacto_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='apellido_paterno',
            new_name='apellido_Paterno',
        ),
    ]
