# Generated by Django 4.2.1 on 2023-06-27 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0009_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='mecanico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.profesional'),
        ),
    ]
