# Generated by Django 4.2.1 on 2023-06-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0011_delete_cargo_profesional_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='contraseña',
            field=models.CharField(max_length=15),
        ),
    ]
