# Generated by Django 4.2.1 on 2023-06-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0012_alter_profesional_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='contraseña',
        ),
    ]
