# Generated by Django 4.2.1 on 2023-06-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0015_alter_profesional_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='foto',
            field=models.ImageField(default=1, upload_to='profesional'),
            preserve_default=False,
        ),
    ]
