# Generated by Django 4.2.1 on 2023-06-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0016_alter_profesional_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='estado',
            field=models.IntegerField(choices=[[0, 'En Espera'], [1, 'Aprobada'], [2, 'Rechazada']], null=True),
        ),
    ]
