# Generated by Django 4.2.1 on 2023-06-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0018_alter_atencion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='motivoRechazo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
