# Generated by Django 4.2.1 on 2023-07-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0019_atencion_motivorechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajaConNostros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.IntegerField(max_length=9)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(max_length=9)),
                ('informacion', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='atencion',
            name='estado',
            field=models.IntegerField(choices=[[0, 'En Espera'], [1, 'Aprobada'], [2, 'Rechazada']], default=0),
        ),
    ]
