# Generated by Django 4.2.1 on 2023-07-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0020_trabajaconnostros_alter_atencion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajaConNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.IntegerField()),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('informacion', models.TextField(max_length=500, verbose_name='Háblanos de ti')),
            ],
        ),
        migrations.DeleteModel(
            name='TrabajaConNostros',
        ),
    ]
