# Generated by Django 4.2.1 on 2023-07-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0021_trabajaconnosotros_delete_trabajaconnostros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajaconnosotros',
            name='nombre',
        ),
        migrations.AddField(
            model_name='trabajaconnosotros',
            name='apellidoMaterno',
            field=models.CharField(max_length=100, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='trabajaconnosotros',
            name='apellidoPaterno',
            field=models.CharField(max_length=100, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='trabajaconnosotros',
            name='nombres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajaconnosotros',
            name='foto',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
