# Generated by Django 4.2.1 on 2023-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0022_remove_trabajaconnosotros_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajaconnosotros',
            name='apellidoMaterno',
            field=models.CharField(max_length=100, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='trabajaconnosotros',
            name='apellidoPaterno',
            field=models.CharField(max_length=100, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='trabajaconnosotros',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trabajaconnosotros',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
    ]
