# Generated by Django 4.2.1 on 2023-07-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0023_alter_trabajaconnosotros_apellidomaterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajaconnosotros',
            name='foto',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
