# Generated by Django 4.2.1 on 2023-07-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0025_alter_trabajaconnosotros_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajaconnosotros',
            name='foto',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
