# Generated by Django 4.2.1 on 2023-07-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0027_alter_atencion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='categoria',
            field=models.IntegerField(choices=[[0, 'Electronica'], [1, 'Cajas de Cambio'], [2, 'Suspensión y Frenos']]),
        ),
    ]
